"""initial schema

Revision ID: 1c040f64f366
Revises: 
Create Date: 2026-06-17 19:22:42.238485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c040f64f366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_ledger_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cache_hits', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('batch_flag', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_ref', sa.String(), nullable=False),
    sa.Column('pipeline_config_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cache_hits', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('model_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_meta',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('tools_allowed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('target_authorizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('scope_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_confirmed', sa.Boolean(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('rate_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('source_tool', sa.String(), nullable=False),
    sa.Column('cwe', sa.String(), nullable=True),
    sa.Column('owasp_category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('exploit_likelihood', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reachability', sa.String(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fix_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_dedup_key'), 'findings', ['dedup_key'], unique=False)
    op.create_table('pattern_findings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('finding_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('test', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('audit_ref', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixes')
    op.drop_table('pattern_findings')
    op.drop_index(op.f('ix_findings_dedup_key'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('target_authorizations')
    op.drop_table('skill_meta')
    op.drop_table('scans')
    op.drop_table('pipeline_configs')
    op.drop_table('cost_ledger_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
