from __future__ import annotations
import base64
import urllib.parse
import pytest
import respx
import httpx
from core.vcs.gitlab import GitLabAdapter
from core.vcs.protocol import VCSError


REPO = "acme/myrepo"
ENCODED_REPO = urllib.parse.quote(REPO, safe="")
TOKEN = "glpat_testtoken"
BASE = "https://gitlab.com/api/v4"


@pytest.fixture
def adapter() -> GitLabAdapter:
    return GitLabAdapter(token=TOKEN, base_url=BASE)


# ── create_branch ─────────────────────────────────────────────────────────────

@respx.mock
async def test_create_branch_success(adapter: GitLabAdapter):
    respx.post(f"{BASE}/projects/{ENCODED_REPO}/repository/branches").mock(
        return_value=httpx.Response(201, json={"name": "argus/fix-deadbeef"})
    )
    await adapter.create_branch(REPO, "argus/fix-deadbeef", "main")


@respx.mock
async def test_create_branch_raises_vcs_error_on_400(adapter: GitLabAdapter):
    respx.post(f"{BASE}/projects/{ENCODED_REPO}/repository/branches").mock(
        return_value=httpx.Response(400, json={"message": "Branch already exists"})
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.create_branch(REPO, "argus/fix-deadbeef", "main")
    assert exc_info.value.status_code == 400


# ── commit_file ───────────────────────────────────────────────────────────────

@respx.mock
async def test_commit_file_success(adapter: GitLabAdapter):
    respx.post(f"{BASE}/projects/{ENCODED_REPO}/repository/commits").mock(
        return_value=httpx.Response(201, json={"id": "abc123"})
    )
    await adapter.commit_file(
        REPO,
        "argus/fix-deadbeef",
        "src/app.py",
        "print('fixed')\n",
        "fix: patch sql injection",
    )


@respx.mock
async def test_commit_file_raises_vcs_error_on_400(adapter: GitLabAdapter):
    respx.post(f"{BASE}/projects/{ENCODED_REPO}/repository/commits").mock(
        return_value=httpx.Response(
            400, json={"message": "A file with this name doesn't exist"}
        )
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.commit_file(REPO, "branch", "src/app.py", "x", "msg")
    assert exc_info.value.status_code == 400


# ── create_pr (merge request) ─────────────────────────────────────────────────

@respx.mock
async def test_create_pr_returns_web_url(adapter: GitLabAdapter):
    respx.post(f"{BASE}/projects/{ENCODED_REPO}/merge_requests").mock(
        return_value=httpx.Response(
            201,
            json={"web_url": "https://gitlab.com/acme/myrepo/-/merge_requests/7"},
        )
    )
    url = await adapter.create_pr(
        REPO,
        "argus/fix-deadbeef",
        "main",
        "fix: sql injection in login",
        "Automated fix generated by Argus.",
    )
    assert url == "https://gitlab.com/acme/myrepo/-/merge_requests/7"


@respx.mock
async def test_create_pr_raises_vcs_error_on_409(adapter: GitLabAdapter):
    respx.post(f"{BASE}/projects/{ENCODED_REPO}/merge_requests").mock(
        return_value=httpx.Response(
            409, json={"message": "Another open merge request already exists"}
        )
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.create_pr(REPO, "head", "main", "title", "body")
    assert exc_info.value.status_code == 409


# ── get_file_content ──────────────────────────────────────────────────────────

@respx.mock
async def test_get_file_content_returns_decoded_string(adapter: GitLabAdapter):
    raw = "def vulnerable(): pass\n"
    encoded = base64.b64encode(raw.encode()).decode()
    encoded_path = urllib.parse.quote("src/app.py", safe="")
    respx.get(
        f"{BASE}/projects/{ENCODED_REPO}/repository/files/{encoded_path}"
    ).mock(
        return_value=httpx.Response(200, json={"content": encoded, "encoding": "base64"})
    )
    content = await adapter.get_file_content(REPO, "src/app.py", ref="main")
    assert content == raw


@respx.mock
async def test_get_file_content_raises_vcs_error_on_404(adapter: GitLabAdapter):
    encoded_path = urllib.parse.quote("missing.py", safe="")
    respx.get(
        f"{BASE}/projects/{ENCODED_REPO}/repository/files/{encoded_path}"
    ).mock(
        return_value=httpx.Response(404, json={"message": "404 File Not Found"})
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.get_file_content(REPO, "missing.py")
    assert exc_info.value.status_code == 404


# ── auth header ───────────────────────────────────────────────────────────────

@respx.mock
async def test_adapter_sends_bearer_token(adapter: GitLabAdapter):
    route = respx.post(
        f"{BASE}/projects/{ENCODED_REPO}/repository/branches"
    ).mock(return_value=httpx.Response(201, json={"name": "argus/fix-x"}))
    await adapter.create_branch(REPO, "argus/fix-x", "main")
    assert route.calls[0].request.headers["authorization"] == f"Bearer {TOKEN}"


# ── self-hosted base URL ──────────────────────────────────────────────────────

@respx.mock
async def test_self_hosted_base_url_is_used():
    adapter = GitLabAdapter(token="tok", base_url="https://gitlab.myco.com/api/v4")
    route = respx.post(
        f"https://gitlab.myco.com/api/v4/projects/{ENCODED_REPO}/repository/branches"
    ).mock(return_value=httpx.Response(201, json={"name": "argus/fix-x"}))
    await adapter.create_branch(REPO, "argus/fix-x", "main")
    assert route.called
