from __future__ import annotations
import base64
import pytest
import respx
import httpx
from core.vcs.github import GitHubAdapter
from core.vcs.protocol import VCSError


OWNER = "acme"
REPO = "myrepo"
REPO_FULL = "acme/myrepo"
TOKEN = "ghp_testtoken"
BASE = "https://api.github.com"


@pytest.fixture
def adapter() -> GitHubAdapter:
    return GitHubAdapter(token=TOKEN)


# ── create_branch ─────────────────────────────────────────────────────────────

@respx.mock
async def test_create_branch_success(adapter: GitHubAdapter):
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/git/refs/heads/main").mock(
        return_value=httpx.Response(200, json={"object": {"sha": "abc123"}})
    )
    respx.post(f"{BASE}/repos/{OWNER}/{REPO}/git/refs").mock(
        return_value=httpx.Response(201, json={"ref": "refs/heads/argus/fix-deadbeef"})
    )
    await adapter.create_branch(REPO_FULL, "argus/fix-deadbeef", "main")


@respx.mock
async def test_create_branch_raises_vcs_error_on_422(adapter: GitHubAdapter):
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/git/refs/heads/main").mock(
        return_value=httpx.Response(200, json={"object": {"sha": "abc123"}})
    )
    respx.post(f"{BASE}/repos/{OWNER}/{REPO}/git/refs").mock(
        return_value=httpx.Response(422, json={"message": "Reference already exists"})
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.create_branch(REPO_FULL, "argus/fix-deadbeef", "main")
    assert exc_info.value.status_code == 422


# ── commit_file ───────────────────────────────────────────────────────────────

@respx.mock
async def test_commit_file_success(adapter: GitHubAdapter):
    file_sha = "fileshaabc"
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/app.py").mock(
        return_value=httpx.Response(200, json={"sha": file_sha})
    )
    respx.put(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/app.py").mock(
        return_value=httpx.Response(200, json={"content": {"sha": "newsha"}})
    )
    await adapter.commit_file(
        REPO_FULL,
        "argus/fix-deadbeef",
        "src/app.py",
        "print('fixed')\n",
        "fix: patch sql injection",
    )


@respx.mock
async def test_commit_file_new_file_no_sha(adapter: GitHubAdapter):
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/new.py").mock(
        return_value=httpx.Response(404, json={"message": "Not Found"})
    )
    respx.put(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/new.py").mock(
        return_value=httpx.Response(201, json={"content": {"sha": "newsha"}})
    )
    await adapter.commit_file(
        REPO_FULL,
        "argus/fix-deadbeef",
        "src/new.py",
        "# new file\n",
        "fix: add missing validation",
    )


@respx.mock
async def test_commit_file_raises_vcs_error_on_403(adapter: GitHubAdapter):
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/app.py").mock(
        return_value=httpx.Response(200, json={"sha": "sha1"})
    )
    respx.put(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/app.py").mock(
        return_value=httpx.Response(403, json={"message": "Forbidden"})
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.commit_file(
            REPO_FULL, "argus/fix-deadbeef", "src/app.py", "x", "msg"
        )
    assert exc_info.value.status_code == 403


# ── create_pr ─────────────────────────────────────────────────────────────────

@respx.mock
async def test_create_pr_returns_url(adapter: GitHubAdapter):
    respx.post(f"{BASE}/repos/{OWNER}/{REPO}/pulls").mock(
        return_value=httpx.Response(
            201,
            json={"html_url": "https://github.com/acme/myrepo/pull/42"},
        )
    )
    url = await adapter.create_pr(
        REPO_FULL,
        "argus/fix-deadbeef",
        "main",
        "fix: sql injection in login",
        "Automated fix generated by Argus.",
    )
    assert url == "https://github.com/acme/myrepo/pull/42"


@respx.mock
async def test_create_pr_raises_vcs_error_on_422(adapter: GitHubAdapter):
    respx.post(f"{BASE}/repos/{OWNER}/{REPO}/pulls").mock(
        return_value=httpx.Response(422, json={"message": "Validation Failed"})
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.create_pr(REPO_FULL, "head", "main", "title", "body")
    assert exc_info.value.status_code == 422


# ── get_file_content ──────────────────────────────────────────────────────────

@respx.mock
async def test_get_file_content_returns_decoded_string(adapter: GitHubAdapter):
    raw = "def vulnerable(): pass\n"
    encoded = base64.b64encode(raw.encode()).decode()
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/contents/src/app.py").mock(
        return_value=httpx.Response(200, json={"content": encoded, "encoding": "base64"})
    )
    content = await adapter.get_file_content(REPO_FULL, "src/app.py", ref="main")
    assert content == raw


@respx.mock
async def test_get_file_content_raises_vcs_error_on_404(adapter: GitHubAdapter):
    respx.get(f"{BASE}/repos/{OWNER}/{REPO}/contents/missing.py").mock(
        return_value=httpx.Response(404, json={"message": "Not Found"})
    )
    with pytest.raises(VCSError) as exc_info:
        await adapter.get_file_content(REPO_FULL, "missing.py")
    assert exc_info.value.status_code == 404


# ── auth header ───────────────────────────────────────────────────────────────

@respx.mock
async def test_adapter_sends_bearer_token(adapter: GitHubAdapter):
    route = respx.get(f"{BASE}/repos/{OWNER}/{REPO}/git/refs/heads/main").mock(
        return_value=httpx.Response(200, json={"object": {"sha": "abc"}})
    )
    respx.post(f"{BASE}/repos/{OWNER}/{REPO}/git/refs").mock(
        return_value=httpx.Response(201, json={})
    )
    await adapter.create_branch(REPO_FULL, "argus/fix-x", "main")
    assert route.calls[0].request.headers["authorization"] == f"Bearer {TOKEN}"
